### ISSUE TITLE
from product backlog to sprint backlog

### ISSUE THREAD

**Issue by hairmenu** [gitscrum-community-edition/laravel-gitscrum#118]
<p>Just new to your project and i like it. But, in my opnion, there are some key feature missing regarding scrum. The most urgent would be to allow a issue defined in the product backlog to get assigned to the sprint. Currently, once the issue is created it is stuck in the product backlog forever.</p>
<p>As a scrum point of view, you build all your product back log with user stories and issues. Then when planning a sprint you pull what you plan to do from this backlog. So </p>
<p>1- On editing an issue, you should be able to assign it to a sprint
2- Wet dream: On the sprint planning page, you add a new column before the TODO. This colum presents all 'not done' User stories with their related issues. Then you can drag-drop the issue to move it to the 'todo' column. That the way you are supposed to build a sprint (well the closest way regarding the gitscrum structure).</p>

**Comment by willianmano** [comment]
Good points. But, the product owner can negotiate with scrum master and the development team and add an issue even if the sprint is running. But this is very, very, very discouraged. But can happen.

I agree with the other points.

**Comment by hairmenu** [comment]
Yes scrum main issue, to my opnion, is the big gap between how it should be and how it's happening.
I forked and will try to push the feature in a few days. Let see what happen :-p
