### ISSUE TITLE
The redirect URI included is not valid.

### ISSUE THREAD

**Issue by CHOMNANP** [gitscrum-community-edition/laravel-gitscrum#157]
<p>Hi,</p>
<p>I have clone, migrate database, and configure GitLab.</p>
<p>I'm trying to sing-in to the app. This my callback url which I pass in GItLab &quot;<a href="http://laravel-gitscrum.dev/auth/provider/gitlab/callback">http://laravel-gitscrum.dev/auth/provider/gitlab/callback</a>&quot;.</p>
<p>I got the error message &quot;The redirect URI included is not valid.&quot;.</p>
<p>Anyone experience this?</p>
<p>Thanks,
Punleu</p>

**Comment by marcoshoo** [comment]
Hi,

I had the same problem. I don't know why but the URI does not pass the validate_redirect_uri method tests of DoorKeeper::OAuth::PreAuthorization class in GitLab. A workaround is force the method to return "true". Go to DoorKeeper gem directory and edit the file "lib/doorkeeper/oauth/pre_authorization.rb":

```
      # TODO: test uri should be matched against the client's one
      def validate_redirect_uri
        return false unless redirect_uri.present?
	  Helpers::URIChecker.valid?(redirect_uri)
#        return false unless redirect_uri.present?
#        Helpers::URIChecker.native_uri?(redirect_uri) ||
#          Helpers::URIChecker.valid_for_authorization?(redirect_uri, client.redirect_uri)
      end
```
Restart GitLab.

**Comment by gkarugi** [comment]
Hi,

I know it's long since and you might have already found a solution.

I recreated this error and it is caused by the APP_URL variable in the  .env file being different from the URL used in the callback gitlab callback URL.

Make sure as described in the documentation that : - http://{URL is the SAME APP_URL}/auth/provider/gitlab/callback
