### ISSUE TITLE
Error ao acessar com github

### ISSUE THREAD

**Issue by victorhugorch** [gitscrum-community-edition/laravel-gitscrum#162]
<h3>Descrição</h3>
<p>Erro ao clicar em fazer login localmente. Instalei a aplicação e passei por todas as etapas.</p>
<ul>
<li>[x] Composer install.</li>
<li>[x] Criar DB</li>
<li>[x] Key:generate</li>
<li>[x] Rodar migrate</li>
<li>[x] Utilizar Docker</li>
</ul>
<p>Tive o mesmo problema que o #6 e rodei a aplicação usando o <code>docker-compose up</code> mas ao tentar logar tive o problema de acesso que a imagem mostra.</p>
<h3>Imagem</h3>
<p><img src="https://cloud.githubusercontent.com/assets/13628253/22706319/ec145222-ed55-11e6-8573-4b75f6434a09.png" alt="image" /></p>

**Comment by renatomarinho** [comment]
Olá @victorhugorch , voce criou a aplicacao no github e inseriu a key no .env?

**Comment by victorhugorch** [comment]
Sim, @renatomarinho , Essa etapa também foi feita.

**Comment by renatomarinho** [comment]
@victorhugorch o que acha de instalar a nova versão do GitScrum?
Se o problema persistir por favor me avise.
abraço.
