### ISSUE TITLE
Why don't you make a language pack

### ISSUE THREAD

**Issue by DukeAnn** [gitscrum-community-edition/laravel-gitscrum#167]
<p>Why not do a language pack, I think language pack can translation is not much.</p>

**Comment by renatomarinho** [comment]
I pushed a branch "feature/language-pack"
In this branch has the languages (https://github.com/renatomarinho/laravel-gitscrum/tree/feature/language-pack/resources/lang)

Example is : https://github.com/renatomarinho/laravel-gitscrum/blob/feature/language-pack/resources/lang/en/gitscrum.php

**Comment by renatomarinho** [comment]
First version to EN language pack : https://github.com/renatomarinho/laravel-gitscrum/commit/d1985ec55cf68839a3932f87eee463a6d0bebc6b

**Comment by DukeAnn** [comment]
Thanks, I'd like to convert the language pack to translate into Chinese

**Comment by renatomarinho** [comment]
@DukeAnn thanks so much!
