### ISSUE TITLE
Sync updates with GitScrum

### ISSUE THREAD

**Issue by renatomarinho** [gitscrum-community-edition/laravel-gitscrum#24]
I belive a possible solution is use the github webhooks to active the sync in the application

**Comment by willianmano** [comment]
What do you mean about sync repositories?

Github hooks is only for individual updates in a single repository. There is two events that the hook can response, "push" and "pull_request".

**Comment by Fitz7** [comment]
does it track pushed branches/PRs with issues?

**Comment by willianmano** [comment]
Eu tava olhando aqui e é possível sim criar os webhooks pra automaticamente enviarem mudanças no github pra aplicação. Vou estudar um pouco mais e ver a possibilidade de implementar.

**Comment by renatomarinho** [comment]
Sim, é possivel. Porém é preciso que a aplicação esteja em um endereço válido, para endereços locais não funcionará, mas acredito que uma ótima solução será uma arquitetura usando websockets

**Comment by timgws** [comment]
@renatomarinho the only issue that is using websockets still does not fully provide a solution. Unless you have a server as an intermediary - something like a proxy that could pass on webhooks from GitHub to private/hosted installs of GitScrum?
