### ISSUE TITLE
Error when process seeders

### ISSUE THREAD

**Issue by meredyk** [gitscrum-community-edition/laravel-gitscrum#260]
When run php artisan migrate:refresh --seed command, the **DatabaseSeeder class does not exist** error is displayed

**Comment by j-s-obrien** [comment]
i had this problem too. Was able to get around it by copying database/seeds/SettingSeeder.php and renaming it as DatabaseSeeder.php. Changed the class name to DatabaseSeeder. Then in my composer.json file make sure autoload, classmap includes the seeder folder, eg. (note i think i'm being redundant with the folders...just wanted to get it to work)
  "autoload": {
        "classmap": [
            "database",
            "app/Models",
            "database/seeds",
            "database/migrations"
        ],

**Comment by meredyk** [comment]
Yeh, I did this to solve the problem. I think I'll send a push to update this inconsistency.
Tnx

**Comment by AgusRdz** [comment]
Just need to run:
`php artisan db:seed --class=SettingSeeder`

**Comment by luizhenriquesoares** [comment]
@AgusRdz  for me, the problem this also is:
> [ReflectionException]               
  Class SettingSeeder does not exist

**Comment by luizhenriquesoares** [comment]
this is work php artisan db:seed

>Seeding: ConfigIssueEffortsTableSeeder
>Seeding: ConfigPrioritiesTableSeeder
>Seeding: IssueTypesTableSeeder
>Seeding: ConfigStatusesTableSeeder

**Comment by renatomarinho** [comment]
Hi @meredyk, 
Can I close the issue?

**Comment by meredyk** [comment]
Yes, please
