### ISSUE TITLE
Undefined property: stdClass::$repositories

### ISSUE THREAD

**Issue by stefanocog** [gitscrum-community-edition/laravel-gitscrum#282]
Have this error when connect to bitbucket and repository list is empty

![selezione_001](https://user-images.githubusercontent.com/4162613/32178340-bf01ceb0-bd8c-11e7-8767-390e9ee4ff29.png)

**Comment by renatomarinho** [comment]
Hi @Te7a-Houdini, 

Can you help him?

Thanks so much!

**Comment by Te7a-Houdini** [comment]
@renatomarinho  yes sure i will take a look

**Comment by renatomarinho** [comment]
@Te7a-Houdini GREAT!
