### ISSUE TITLE
QueryException Error

### ISSUE THREAD

**Issue by muhammadshoaibwardak** [gitscrum-community-edition/laravel-gitscrum#284]
This Error occurred when creating Product Backlog.

`SQLSTATE[HY000]: General error: 1364 Field 'provider_id' doesn't have a default value (SQL: insert into `product_backlogs` (`is_api`, `organization_id`, `title`, `description`, `user_id`, `slug`, `updated_at`, `created_at`) values (1, 1, Test, sdf, 1, test-5a04257490ce7, 2017-11-09 09:52:52, 2017-11-09 09:52:52))`

**Comment by renatomarinho** [comment]
@muhammadshoaibwardak  bug fixed.
Thanks for you collaboration.
