### ISSUE TITLE
Can we use this with bitbucket repos?

### ISSUE THREAD

**Issue by iampawan31** [gitscrum-community-edition/laravel-gitscrum#36]
I was wondering if we can use this for private repos on bitbucket.

**Comment by renatomarinho** [comment]
Yet not, but it feature is on backlog product.

**Comment by rafwell** [comment]
+1

**Comment by paulocastellano** [comment]
+1

**Comment by hashid** [comment]
+1

**Comment by wimurk** [comment]
can you add bitbucket?

**Comment by renatomarinho** [comment]
@wimurk @hashid @paulocastellano @rafwell @iampawan31 
:) solved
