### ISSUE TITLE
Bitbucket support?

### ISSUE THREAD

**Issue by SiliticX** [gitscrum-community-edition/laravel-gitscrum#50]
Is this in the plans? As a company that entire's infrastructure is on bitbucket this would be REALLY appreciated.

**Comment by renatomarinho** [comment]
Yes, it is in product backlog

**Comment by paulocastellano** [comment]
+1

**Comment by victorfcm** [comment]
I'm working on the gitlab provider, and i'm doing everything I can to do it flexible to be as easy as it can be to add new providers.

**Comment by ejlocop** [comment]
+1

**Comment by angelomr** [comment]
+1

**Comment by harrysbaraini** [comment]
Hi. I forked this repo and started working on Bitbucket support. I can manage to login using Bitbucket, but no success when requesting repositories. It seems something related to GitScrum's Helper class which uses HTTP Basic when making requests to the git provider. When I pass _false_ to second argument on Helper::request, BitBucket returns some info, but no repo.

Any idea @victorfcm ?

**Comment by deleugpn** [comment]
+1

**Comment by cowboymathu** [comment]
+1

**Comment by cognitus** [comment]
any news about this?

**Comment by Wijnands** [comment]
+1

**Comment by pdifeo** [comment]
+1

**Comment by Atles** [comment]
@renatomarinho, do you have any news about this? laravel-gitscrum is amazing.

**Comment by rafaelmontarroyos** [comment]
+1

**Comment by renatomarinho** [comment]
@done :)!!!
