### ISSUE TITLE
Gitscrum to our gitscrum

### ISSUE THREAD

**Issue by victorfcm** [gitscrum-community-edition/laravel-gitscrum#70]
@renatomarinho Could you put a live version of the GitScrum online and connected to this repo? So we can followup the issues and help to improve the code :)

**Comment by yinx** [comment]
I really like this idea!

**Comment by victorfcm** [comment]
That will work also as a live demo, that was requested in 2 issues :)

**Comment by jamesaspence** [comment]
As somebody who is keenly watching this and thinking about improvements, this would help me get contributing too! I have ideas :)
